name: 'KIIK SOLUCOES E SERVICOS DE PAGAMENTO LTDA'
document: '19257959000135'
bank_account:
  code: '341'
  branch: '0609'
  digit: '1'
  number: '08003'
address:
  street: 'R MARANHAO 598'
  number: '600'
  city: 'SAO PAULO'
  zip: '01240000'
  state: 'SP'
